name = "cf-img-img"
main = "src/worker.js"
compatibility_date = "2026-07-29"

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
